Traceback (most recent call last):
  File "/home/james/Desktop/python-auth-tools/test.py", line 184, in <module>
    test_render_main()
  File "/home/james/Desktop/python-auth-tools/test.py", line 16, in test_render_main
    assert render_main(title="main") == ''
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
